kind: Service
apiVersion: v1
metadata:
  name: pipeline-httpserver
  namespace: satomicapp
spec:
  selector:
    app: pipeline-httpserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: satomicapp
  name: pipeline-httpserver
  labels:
    app: pipeline-httpserver
    version: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-httpserver
      version: develop
  template:
    metadata:
      labels:
        app: pipeline-httpserver
        version: develop
    spec:
      containers:
      - name: pipeline-httpserver
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
